openiked/openiked-portable

iked/pfkey.c

Make sure to bzero udpencap message before 'goto send' in SADB_DELETE case.

Fix SADB_DELETE bug for OpenBSD and FreeBSD.

---

iked/pfkey.c

Fix sa_pxy check. if(SS_LEN(spxy)) does not work with the macro.

---

CMakeLists.txt
iked/config.c
iked/dh.c
iked/dh.h
iked/iked.h
iked/ikev2.c
iked/parse.y
iked/pfkey.c
iked/proc.c
iked/util.c
regress/parser/common.c

- Fix format string warnings
- include "grp.h" on linux fro setgroups()
- rename dh.h `struct group` to `struct dh_group` to prevent name conflict
- `#ifdef` around variables in pfkey to prevent unused variable warnings

Fix most compiler warnings in iked and compat

---

iked/parse.y
iked/pfkey.c

- Disable broken transforms on linux by default.
- Make sure not to use ESN with unsupported kernels.
- Avoid non-standard SHA256 on linux.

Fix Linux defaults.

---

.github/workflows/cmake.yml
CMakeLists.txt
iked/ca.c
iked/crypto.c
iked/dh.c
regress/dh/CMakeLists.txt
regress/dh/dhtest.c

- Fix errors introduced with switch to OpenSSL 1.1 API
- build Diffie-Hellman test in `regress/dhtest` (which found the bug)
- run `dhtest` with CI to catch future errors in dh.c

Fix OpenSSL 1.1 API errors

---

iked/dh.c

`EC_POINT_get_affine_coordinates_GFp()` and `EC_POINT_get_affine_coordinates_GFm2()`
are the same thing, but the `_GFm2()` variant can be disabled with `-DOPENSSL_NO_EC2M`.
Always use `_GFp()` to fix compilation with `NO_ECM` OpenSSL builds.
Should fix #31

Fix compilation with -DOPENSSL_NO_EC2M

---

ikectl/ikeca.c

This was the result of a hack that was needed to get ikectl to compile on linux.
Clean up the hack while we're at it.

Fix unused variable saved_errno

---

ikectl/ikeca.c

Fixes all the compiler warnings in ikectl.

Check snprintf return values.

---

iked/config.c
iked/iked.c
iked/iked.h
iked/ikev2.c
iked/pfkey.c

- When using udpencap, set the `ESPINUDP` sockopt on both listen and send sock. Unbreaks udpencap as responder.
- On Linux, add a flow of type `IPSEC_DIR_FWD` to allow forwarding of IPsec traffic.

Fix remaining Linux bugs

---

iked/ikev2.c

Fixes a bug with broken FWD flows on linux.

Just copy the IN flow for FWD instead of setting everything twice.

---

regress/parser-libfuzzer/common.c
regress/parser-libfuzzer/run_test.sh
regress/parser-libfuzzer/test_parser_fuzz.c

add a stub function in common.c to correctly free ikev2-msg in the libfuzzer-test.
this should fix #35

libfuzzer: fix false-positive memory leak in ikev2_msg

---

iked/iked.c

The default is 0, which makes receiving udpencap impossible in
the standard configuration.

Explicitly set net.inet.ipsec.esp_port sysctl on Apple.

---

iked/pfkey.c

For policy_test() to find a matching flow, flow_rdomain and flow_saproto need to be set accordingly.
Fixes #72.

Fix acquire on non-OpenBSD systems.

---

.github/workflows/cmake.yml

The `macos-10.15` runners will soon be unavailable. Fortunately, the `macos-12` runners are an easy drop-in replacement.

Fix BSD CI to upgrading to newer `macos-12` runner.

---

CMakeLists.txt

for macOS on arm64 homebrew uses different paths for installed libraries (https://github.com/Homebrew/brew/pull/9117). To get openiked-portable into the homebew package-manager, we need an option to use the native homebrew-libraries on arm64 (e.g. openssl).

add build-option for arm64-macOS with homebrew

---

iked/pfkey.c

Invert nat_sport and nat_dport for outgoing SAs in the FreeBSD/NetBSD/Linux extension for udpencap.
Fixes #93

Fix udpencap source and destination ports.

---

ikectl/ikectl.c

gcc 11.2.1 and 12.2.0 x86_64:
warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]

[ikectl] build warning fix: second argument has type uint64_t

---

.github/workflows/cmake.yml
iked/CMakeLists.txt
iked/vroute-netlink.c

Construct our own dbus messages for setting name servers and search domains. This allows us to drop a exec call for resolvectl and should be easier to extend in the future.

Use libsystemd to directly send dbus messages

---

iked/vroute-netlink.c

move sd_bus_open_system() to vroute_do_dns(), otherwise we keep the dbus handle for the lifetime of iked and dbus calls fail with ENOTCONN.
the dbus handle could also be moved to the stack instead.
maybe ENTOCONN is triggered if a dbus component restarts?

iked: fix vroute_dbus_dns: System.Error.ENOTCONN

---

CMakeLists.txt

This is what happens currently:
```
kind: "try_compile-v1"
backtrace:
- "/opt/local/share/cmake-3.31/Modules/CheckIncludeFiles.cmake:141 (try_compile)"
- "CMakeLists.txt:137 (check_include_files)"
checks:
- "Looking for include file netinet6/ipsec.h"
directories:
source: "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_openiked/openiked/work/build/CMakeFiles/CMakeScratch/TryCompile-wIY0xP"
binary: "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_openiked/openiked/work/build/CMakeFiles/CMakeScratch/TryCompile-wIY0xP"
cmakeVariables:
CMAKE_C_FLAGS: "-pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include"
CMAKE_C_FLAGS_DEBUG: "-g"
CMAKE_EXE_LINKER_FLAGS: "-L/opt/local/libexec/openssl3/lib …
```

CMakeLists: fix detection of netinet6/ipsec.h

---

iked/vroute.c

Fixes this error:
```
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_openiked/openiked/work/openiked-portable-7.4/iked/vroute.c:21:
/usr/include/net/if.h:265:34: error: field 'ifru_addr' has incomplete type
265 |                 struct  sockaddr ifru_addr;
|                                  ^~~~~~~~~
/usr/include/net/if.h:266:34: error: field 'ifru_dstaddr' has incomplete type
266 |                 struct  sockaddr ifru_dstaddr;
|                                  ^~~~~~~~~~~~
/usr/include/net/if.h:267:34: error: field 'ifru_broadaddr' has incomplete type
267 |                 struct  sockaddr ifru_broadaddr;
|                                  ^~~~~~~~~~~~~~
/usr/include/net/if.h:308:26: error: field 'ifra_addr' has incomplete type
308 |         struct …
```

vroute.c: include sys/socket.h on macOS
